### PR TITLE
issue-43 Delete an existing delta and delete delta bucket file before writing to it in a task.

### LINKED ISSUE #43: Handle task retries gracefully in Spark ACID OSS
Tasks writing data into Hive ACID if failed then would be retried like normal Spark Tasks. But if failed task would have created bucket file under delta directory, then new task would fail like specified in this issue: #41

In Qubole's Hive fork are overwriting the file instead of throwing error and hence things work. We need to solve this for Open source.

### PR DESCRIPTION
**Pull request by amoghmargoor**
Deletion of existing delta and delete delta bucket files before starting the write is required as Hive's OrcRecordUpdater
doesnot expect it to be present and hence fails. They can pre exist in the case of task retries, so they need to be cleaned up.

### CODE REVIEW

**Comment by amoghmargoor** [comment]
@sourabh912 can you review ?

File: src/main/scala/com/qubole/spark/hiveacid/writer/hive/HiveAcidWriter.scala [hunk 1]
```diff
@@ -221,12 +221,33 @@ private[writer] class HiveAcidFullAcidWriter(options: WriterOptions,
       }
     }
 
+    def safeDeletePath(fs: FileSystem, path: Path): Boolean = {
+      try {
+        fs.delete(path, false)
```
Comment (sourabh912) [inline src/main/scala/com/qubole/spark/hiveacid/writer/hive/HiveAcidWriter.scala]: @amoghmargoor : Should we do this ? 

`if(fs.exists(path)) {
    fs.delete(path, false)
 }`

Since fs.exist() does filestatus() call whereas delete() first calls filestatus() and then delete(). Assuming that in most of the cases task retries won't happen - we would only end up making getFileStatus().

File: src/main/scala/com/qubole/spark/hiveacid/writer/hive/HiveAcidWriter.scala [hunk 2]
```diff
@@ -221,12 +221,33 @@ private[writer] class HiveAcidFullAcidWriter(options: WriterOptions,
       }
     }
 
+    def safeDeletePath(fs: FileSystem, path: Path): Boolean = {
```
Comment (sourabh912) [inline src/main/scala/com/qubole/spark/hiveacid/writer/hive/HiveAcidWriter.scala]: nit: make it private?

Comment (sourabh912) [reply src/main/scala/com/qubole/spark/hiveacid/writer/hive/HiveAcidWriter.scala]: nvm. this is already inside `createWriter`

File: src/main/scala/com/qubole/spark/hiveacid/writer/hive/HiveAcidWriter.scala [hunk 3]
```diff
@@ -221,12 +221,33 @@ private[writer] class HiveAcidFullAcidWriter(options: WriterOptions,
...
+        safeDeletePath(fs, deltaPath)
+      }
       createVersionFile(acidOutputFormatOptions)
     }
 
     if (createDeleteDelta) {
-      createVersionFile(acidOutputFormatOptions.writingDeleteDelta(true))
+      // Delete delete_delta bucket file if it exists. It can exist in the cases of task retries.
+      val deleteDeltaOptions = acidOutputFormatOptions.clone().writingDeleteDelta(true)
+      val deleteDeltaPath = AcidUtils.createFilename(path, deleteDeltaOptions)
```
Comment (sourabh912) [inline src/main/scala/com/qubole/spark/hiveacid/writer/hive/HiveAcidWriter.scala]: nit: rename it to deleteDeltaBucketFilePath?

Comment (amoghmargoor) [reply src/main/scala/com/qubole/spark/hiveacid/writer/hive/HiveAcidWriter.scala]: done

File: src/main/scala/com/qubole/spark/hiveacid/writer/hive/HiveAcidWriter.scala (hunk 1 above)
Comment (amoghmargoor) [reply src/main/scala/com/qubole/spark/hiveacid/writer/hive/HiveAcidWriter.scala]: done.
